[project]
name = "monitoring-1-get-started"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.6"
dependencies = [
    "evidently>=0.7.5",
    "great-expectations>=1.4.5",
    "mlflow>=2.22.0",
    "pendulum>=3.1.0",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "ruff>=0.11.11",
]
